name: Deploy with Terraform

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download image info
        uses: actions/download-artifact@v4
        with:
          name: image-info
          path: ./artifact

      - name: Display downloaded files
        run: |
          echo "Files in artifact directory:"
          ls -l ./artifact
          cat ./artifact/image.txt || echo "image.txt not found"

      - name: Set image_url as environment variable
        run: |
          IMAGE_URL=$(cat ./artifact/image.txt)
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      - name: Checkout repo (to get Terraform files)
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_url=${{ env.IMAGE_URL }}"
        working-directory: terraform

