name: Deploy with Terraform

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      TF_VAR_image_tag: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Optional: Import existing resources only if not in Terraform state
      - name: Import existing AWS resources (Optional)
        run: |
          terraform import aws_lb.strapi arn:aws:elasticloadbalancing:us-east-1:607700977843:loadbalancer/app/strapi-alb/653ce13d206cc605 || true
          terraform import aws_lb_listener.http arn:aws:elasticloadbalancing:us-east-1:607700977843:listener/app/strapi-alb/653ce13d206cc605/a4ca562d1d60c43a || true
          terraform import aws_ecs_cluster.strapi strapi-cluster || true
          terraform import aws_security_group.alb_sg sg-02572b17993127d6c || true
          terraform import aws_codedeploy_app.strapi StrapiApp || true
          terraform import aws_iam_role.ecs_task_execution ecsTaskExecutionRole || true
          terraform import aws_iam_role.codedeploy CodeDeployServiceRole || true
          terraform import aws_ecs_service.strapi strapi-cluster/strapi-service || true
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var="image_tag=${{ env.TF_VAR_image_tag }}"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ env.TF_VAR_image_tag }}"
        working-directory: terraform
