name: Deploy with Terraform

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download image URL
        uses: actions/download-artifact@v3
        with:
          name: image-info

      - name: Read image.txt
        id: image
        run: |
          IMAGE=$(cat image.txt | cut -d'=' -f2)
          echo "IMAGE_URL=$IMAGE" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.5

      - name: Init Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve -var="image_url=${{ env.IMAGE_URL }}"
        working-directory: terraform
