name: Deploy with Terraform

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      TF_VAR_image_tag: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Import ALB
        run: terraform import aws_lb.strapi arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/strapi-alb/abcd1234efgh5678
        working-directory: terraform
        continue-on-error: true

      - name: Import Blue Target Group
        run: terraform import aws_lb_target_group.blue arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/strapi-blue/xyz
        working-directory: terraform
        continue-on-error: true

      - name: Import Green Target Group
        run: terraform import aws_lb_target_group.green arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/strapi-green/abc
        working-directory: terraform
        continue-on-error: true

      - name: Import ALB Listener
        run: terraform import aws_lb_listener.http arn:aws:elasticloadbalancing:us-east-1:123456789012:listener/app/strapi-alb/abcd1234efgh5678/abcd1234
        working-directory: terraform
        continue-on-error: true

      - name: Import ECS Cluster
        run: terraform import aws_ecs_cluster.strapi strapi-cluster
        working-directory: terraform
        continue-on-error: true

      - name: Import ECS Service
        run: terraform import aws_ecs_service.strapi strapi-cluster/strapi-service
        working-directory: terraform
        continue-on-error: true

      - name: Import ECS Task Definition
        run: terraform import aws_ecs_task_definition.strapi strapi:5
        working-directory: terraform
        continue-on-error: true

      - name: Import CodeDeploy Application
        run: terraform import aws_codedeploy_app.strapi strapi-codedeploy-app
        working-directory: terraform
        continue-on-error: true

      - name: Import CodeDeploy Deployment Group
        run: terraform import aws_codedeploy_deployment_group.strapi strapi-codedeploy-app/strapi-deployment-group
        working-directory: terraform
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -var="image_tag=${{ env.TF_VAR_image_tag }}"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ env.TF_VAR_image_tag }}"
        working-directory: terraform

