name: Deploy Strapi on EC2 using Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="docker_image_url=${{ secrets.DOCKER_IMAGE_URL }}" \
            -var="subnet_id=${{ secrets.SUBNET_ID }}" \
            -var="vpc_id=${{ secrets.VPC_ID }}" \
            -var="public_key_path=${{ secrets.PUBLIC_KEY_PATH }}"
        working-directory: ./terraform

